export type SurahMeta = {
  id: number;
  nameArabic: string;
  nameEnglish: string;
  translation: string;
  revelation: "Makkah" | "Madinah";
  ayahCount: number;
};

// Source: standard Quran surah metadata
export const SURAHS: SurahMeta[] = [
  { id: 1, nameArabic: "الفاتحة", nameEnglish: "Al Fatihah", translation: "The Opener", revelation: "Makkah", ayahCount: 7 },
  { id: 2, nameArabic: "البقرة", nameEnglish: "Al Baqarah", translation: "The Cow", revelation: "Madinah", ayahCount: 286 },
  { id: 3, nameArabic: "آل عمران", nameEnglish: "Al Imran", translation: "Family of Imran", revelation: "Madinah", ayahCount: 200 },
  { id: 4, nameArabic: "النساء", nameEnglish: "An Nisa", translation: "The Women", revelation: "Madinah", ayahCount: 176 },
  { id: 5, nameArabic: "المائدة", nameEnglish: "Al Ma'idah", translation: "The Table Spread", revelation: "Madinah", ayahCount: 120 },
  { id: 6, nameArabic: "الأنعام", nameEnglish: "Al An'am", translation: "The Cattle", revelation: "Makkah", ayahCount: 165 },
  { id: 7, nameArabic: "الأعراف", nameEnglish: "Al A'raf", translation: "The Heights", revelation: "Makkah", ayahCount: 206 },
  { id: 8, nameArabic: "الأنفال", nameEnglish: "Al Anfal", translation: "The Spoils of War", revelation: "Madinah", ayahCount: 75 },
  { id: 9, nameArabic: "التوبة", nameEnglish: "At Tawbah", translation: "The Repentance", revelation: "Madinah", ayahCount: 129 },
  { id: 10, nameArabic: "يونس", nameEnglish: "Yunus", translation: "Jonah", revelation: "Makkah", ayahCount: 109 },
  { id: 11, nameArabic: "هود", nameEnglish: "Hud", translation: "Hud", revelation: "Makkah", ayahCount: 123 },
  { id: 12, nameArabic: "يوسف", nameEnglish: "Yusuf", translation: "Joseph", revelation: "Makkah", ayahCount: 111 },
  { id: 13, nameArabic: "الرعد", nameEnglish: "Ar Ra'd", translation: "The Thunder", revelation: "Madinah", ayahCount: 43 },
  { id: 14, nameArabic: "إبراهيم", nameEnglish: "Ibrahim", translation: "Abraham", revelation: "Makkah", ayahCount: 52 },
  { id: 15, nameArabic: "الحجر", nameEnglish: "Al Hijr", translation: "The Rocky Tract", revelation: "Makkah", ayahCount: 99 },
  { id: 16, nameArabic: "النحل", nameEnglish: "An Nahl", translation: "The Bee", revelation: "Makkah", ayahCount: 128 },
  { id: 17, nameArabic: "الإسراء", nameEnglish: "Al Isra", translation: "The Night Journey", revelation: "Makkah", ayahCount: 111 },
  { id: 18, nameArabic: "الكهف", nameEnglish: "Al Kahf", translation: "The Cave", revelation: "Makkah", ayahCount: 110 },
  { id: 19, nameArabic: "مريم", nameEnglish: "Maryam", translation: "Mary", revelation: "Makkah", ayahCount: 98 },
  { id: 20, nameArabic: "طه", nameEnglish: "Ta-Ha", translation: "Ta-Ha", revelation: "Makkah", ayahCount: 135 },
  { id: 21, nameArabic: "الأنبياء", nameEnglish: "Al Anbiya", translation: "The Prophets", revelation: "Makkah", ayahCount: 112 },
  { id: 22, nameArabic: "الحج", nameEnglish: "Al Hajj", translation: "The Pilgrimage", revelation: "Madinah", ayahCount: 78 },
  { id: 23, nameArabic: "المؤمنون", nameEnglish: "Al Mu'minun", translation: "The Believers", revelation: "Makkah", ayahCount: 118 },
  { id: 24, nameArabic: "النور", nameEnglish: "An Nur", translation: "The Light", revelation: "Madinah", ayahCount: 64 },
  { id: 25, nameArabic: "الفرقان", nameEnglish: "Al Furqan", translation: "The Criterion", revelation: "Makkah", ayahCount: 77 },
  { id: 26, nameArabic: "الشعراء", nameEnglish: "Ash Shu'ara", translation: "The Poets", revelation: "Makkah", ayahCount: 227 },
  { id: 27, nameArabic: "النمل", nameEnglish: "An Naml", translation: "The Ant", revelation: "Makkah", ayahCount: 93 },
  { id: 28, nameArabic: "القصص", nameEnglish: "Al Qasas", translation: "The Stories", revelation: "Makkah", ayahCount: 88 },
  { id: 29, nameArabic: "العنكبوت", nameEnglish: "Al Ankabut", translation: "The Spider", revelation: "Makkah", ayahCount: 69 },
  { id: 30, nameArabic: "الروم", nameEnglish: "Ar Rum", translation: "The Romans", revelation: "Makkah", ayahCount: 60 },
  { id: 31, nameArabic: "لقمان", nameEnglish: "Luqman", translation: "Luqman", revelation: "Makkah", ayahCount: 34 },
  { id: 32, nameArabic: "السجدة", nameEnglish: "As Sajdah", translation: "The Prostration", revelation: "Makkah", ayahCount: 30 },
  { id: 33, nameArabic: "الأحزاب", nameEnglish: "Al Ahzab", translation: "The Combined Forces", revelation: "Madinah", ayahCount: 73 },
  { id: 34, nameArabic: "سبأ", nameEnglish: "Saba", translation: "Sheba", revelation: "Makkah", ayahCount: 54 },
  { id: 35, nameArabic: "فاطر", nameEnglish: "Fatir", translation: "Originator", revelation: "Makkah", ayahCount: 45 },
  { id: 36, nameArabic: "يس", nameEnglish: "Ya-Sin", translation: "Ya Sin", revelation: "Makkah", ayahCount: 83 },
  { id: 37, nameArabic: "الصافات", nameEnglish: "As Saffat", translation: "Those Who Set the Ranks", revelation: "Makkah", ayahCount: 182 },
  { id: 38, nameArabic: "ص", nameEnglish: "Sad", translation: "Sad", revelation: "Makkah", ayahCount: 88 },
  { id: 39, nameArabic: "الزمر", nameEnglish: "Az Zumar", translation: "The Troops", revelation: "Makkah", ayahCount: 75 },
  { id: 40, nameArabic: "غافر", nameEnglish: "Ghafir", translation: "The Forgiver", revelation: "Makkah", ayahCount: 85 },
  { id: 41, nameArabic: "فصلت", nameEnglish: "Fussilat", translation: "Explained in Detail", revelation: "Makkah", ayahCount: 54 },
  { id: 42, nameArabic: "الشورى", nameEnglish: "Ash Shura", translation: "The Consultation", revelation: "Makkah", ayahCount: 53 },
  { id: 43, nameArabic: "الزخرف", nameEnglish: "Az Zukhruf", translation: "The Ornaments of Gold", revelation: "Makkah", ayahCount: 89 },
  { id: 44, nameArabic: "الدخان", nameEnglish: "Ad Dukhan", translation: "The Smoke", revelation: "Makkah", ayahCount: 59 },
  { id: 45, nameArabic: "الجاثية", nameEnglish: "Al Jathiyah", translation: "The Crouching", revelation: "Makkah", ayahCount: 37 },
  { id: 46, nameArabic: "الأحقاف", nameEnglish: "Al Ahqaf", translation: "The Wind-Curved Sandhills", revelation: "Makkah", ayahCount: 35 },
  { id: 47, nameArabic: "محمد", nameEnglish: "Muhammad", translation: "Muhammad", revelation: "Madinah", ayahCount: 38 },
  { id: 48, nameArabic: "الفتح", nameEnglish: "Al Fath", translation: "The Victory", revelation: "Madinah", ayahCount: 29 },
  { id: 49, nameArabic: "الحجرات", nameEnglish: "Al Hujurat", translation: "The Rooms", revelation: "Madinah", ayahCount: 18 },
  { id: 50, nameArabic: "ق", nameEnglish: "Qaf", translation: "Qaf", revelation: "Makkah", ayahCount: 45 },
  { id: 51, nameArabic: "الذاريات", nameEnglish: "Adh Dhariyat", translation: "The Winnowing Winds", revelation: "Makkah", ayahCount: 60 },
  { id: 52, nameArabic: "الطور", nameEnglish: "At Tur", translation: "The Mount", revelation: "Makkah", ayahCount: 49 },
  { id: 53, nameArabic: "النجم", nameEnglish: "An Najm", translation: "The Star", revelation: "Makkah", ayahCount: 62 },
  { id: 54, nameArabic: "القمر", nameEnglish: "Al Qamar", translation: "The Moon", revelation: "Makkah", ayahCount: 55 },
  { id: 55, nameArabic: "الرحمن", nameEnglish: "Ar Rahman", translation: "The Beneficent", revelation: "Madinah", ayahCount: 78 },
  { id: 56, nameArabic: "الواقعة", nameEnglish: "Al Waqi'ah", translation: "The Inevitable", revelation: "Makkah", ayahCount: 96 },
  { id: 57, nameArabic: "الحديد", nameEnglish: "Al Hadid", translation: "The Iron", revelation: "Madinah", ayahCount: 29 },
  { id: 58, nameArabic: "المجادلة", nameEnglish: "Al Mujadilah", translation: "The Pleading Woman", revelation: "Madinah", ayahCount: 22 },
  { id: 59, nameArabic: "الحشر", nameEnglish: "Al Hashr", translation: "The Exile", revelation: "Madinah", ayahCount: 24 },
  { id: 60, nameArabic: "الممتحنة", nameEnglish: "Al Mumtahanah", translation: "She That Is to Be Examined", revelation: "Madinah", ayahCount: 13 },
  { id: 61, nameArabic: "الصف", nameEnglish: "As Saff", translation: "The Ranks", revelation: "Madinah", ayahCount: 14 },
  { id: 62, nameArabic: "الجمعة", nameEnglish: "Al Jumu'ah", translation: "The Congregation, Friday", revelation: "Madinah", ayahCount: 11 },
  { id: 63, nameArabic: "المنافقون", nameEnglish: "Al Munafiqun", translation: "The Hypocrites", revelation: "Madinah", ayahCount: 11 },
  { id: 64, nameArabic: "التغابن", nameEnglish: "At Taghabun", translation: "The Mutual Disillusion", revelation: "Madinah", ayahCount: 18 },
  { id: 65, nameArabic: "الطلاق", nameEnglish: "At Talaq", translation: "The Divorce", revelation: "Madinah", ayahCount: 12 },
  { id: 66, nameArabic: "التحريم", nameEnglish: "At Tahrim", translation: "The Prohibition", revelation: "Madinah", ayahCount: 12 },
  { id: 67, nameArabic: "الملك", nameEnglish: "Al Mulk", translation: "The Sovereignty", revelation: "Makkah", ayahCount: 30 },
  { id: 68, nameArabic: "القلم", nameEnglish: "Al Qalam", translation: "The Pen", revelation: "Makkah", ayahCount: 52 },
  { id: 69, nameArabic: "الحاقة", nameEnglish: "Al Haqqah", translation: "The Reality", revelation: "Makkah", ayahCount: 52 },
  { id: 70, nameArabic: "المعارج", nameEnglish: "Al Ma'arij", translation: "The Ascending Stairways", revelation: "Makkah", ayahCount: 44 },
  { id: 71, nameArabic: "نوح", nameEnglish: "Nuh", translation: "Noah", revelation: "Makkah", ayahCount: 28 },
  { id: 72, nameArabic: "الجن", nameEnglish: "Al Jinn", translation: "The Jinn", revelation: "Makkah", ayahCount: 28 },
  { id: 73, nameArabic: "المزمل", nameEnglish: "Al Muzzammil", translation: "The Enshrouded One", revelation: "Makkah", ayahCount: 20 },
  { id: 74, nameArabic: "المدثر", nameEnglish: "Al Muddaththir", translation: "The Cloaked One", revelation: "Makkah", ayahCount: 56 },
  { id: 75, nameArabic: "القيامة", nameEnglish: "Al Qiyamah", translation: "The Resurrection", revelation: "Makkah", ayahCount: 40 },
  { id: 76, nameArabic: "الإنسان", nameEnglish: "Al Insan", translation: "The Man", revelation: "Madinah", ayahCount: 31 },
  { id: 77, nameArabic: "المرسلات", nameEnglish: "Al Mursalat", translation: "The Emissaries", revelation: "Makkah", ayahCount: 50 },
  { id: 78, nameArabic: "النبأ", nameEnglish: "An Naba", translation: "The Tidings", revelation: "Makkah", ayahCount: 40 },
  { id: 79, nameArabic: "النازعات", nameEnglish: "An Nazi'at", translation: "Those Who Drag Forth", revelation: "Makkah", ayahCount: 46 },
  { id: 80, nameArabic: "عبس", nameEnglish: "Abasa", translation: "He Frowned", revelation: "Makkah", ayahCount: 42 },
  { id: 81, nameArabic: "التكوير", nameEnglish: "At Takwir", translation: "The Overthrowing", revelation: "Makkah", ayahCount: 29 },
  { id: 82, nameArabic: "الانفطار", nameEnglish: "Al Infitar", translation: "The Cleaving", revelation: "Makkah", ayahCount: 19 },
  { id: 83, nameArabic: "المطففين", nameEnglish: "Al Mutaffifin", translation: "Defrauding", revelation: "Makkah", ayahCount: 36 },
  { id: 84, nameArabic: "الانشقاق", nameEnglish: "Al Inshiqaq", translation: "The Splitting Open", revelation: "Makkah", ayahCount: 25 },
  { id: 85, nameArabic: "البروج", nameEnglish: "Al Buruj", translation: "The Mansions of the Stars", revelation: "Makkah", ayahCount: 22 },
  { id: 86, nameArabic: "الطارق", nameEnglish: "At Tariq", translation: "The Morning Star", revelation: "Makkah", ayahCount: 17 },
  { id: 87, nameArabic: "الأعلى", nameEnglish: "Al A'la", translation: "The Most High", revelation: "Makkah", ayahCount: 19 },
  { id: 88, nameArabic: "الغاشية", nameEnglish: "Al Ghashiyah", translation: "The Overwhelming", revelation: "Makkah", ayahCount: 26 },
  { id: 89, nameArabic: "الفجر", nameEnglish: "Al Fajr", translation: "The Dawn", revelation: "Makkah", ayahCount: 30 },
  { id: 90, nameArabic: "البلد", nameEnglish: "Al Balad", translation: "The City", revelation: "Makkah", ayahCount: 20 },
  { id: 91, nameArabic: "الشمس", nameEnglish: "Ash Shams", translation: "The Sun", revelation: "Makkah", ayahCount: 15 },
  { id: 92, nameArabic: "الليل", nameEnglish: "Al Layl", translation: "The Night", revelation: "Makkah", ayahCount: 21 },
  { id: 93, nameArabic: "الضحى", nameEnglish: "Ad Duha", translation: "The Morning Hours", revelation: "Makkah", ayahCount: 11 },
  { id: 94, nameArabic: "الشرح", nameEnglish: "Ash Sharh", translation: "The Relief", revelation: "Makkah", ayahCount: 8 },
  { id: 95, nameArabic: "التين", nameEnglish: "At Tin", translation: "The Fig", revelation: "Makkah", ayahCount: 8 },
  { id: 96, nameArabic: "العلق", nameEnglish: "Al Alaq", translation: "The Clot", revelation: "Makkah", ayahCount: 19 },
  { id: 97, nameArabic: "القدر", nameEnglish: "Al Qadr", translation: "The Power", revelation: "Makkah", ayahCount: 5 },
  { id: 98, nameArabic: "البينة", nameEnglish: "Al Bayyinah", translation: "The Clear Proof", revelation: "Madinah", ayahCount: 8 },
  { id: 99, nameArabic: "الزلزلة", nameEnglish: "Az Zalzalah", translation: "The Earthquake", revelation: "Madinah", ayahCount: 8 },
  { id: 100, nameArabic: "العاديات", nameEnglish: "Al Adiyat", translation: "The Courser", revelation: "Makkah", ayahCount: 11 },
  { id: 101, nameArabic: "القارعة", nameEnglish: "Al Qari'ah", translation: "The Calamity", revelation: "Makkah", ayahCount: 11 },
  { id: 102, nameArabic: "التكاثر", nameEnglish: "At Takathur", translation: "The Rivalry in World Increase", revelation: "Makkah", ayahCount: 8 },
  { id: 103, nameArabic: "العصر", nameEnglish: "Al Asr", translation: "The Declining Day", revelation: "Makkah", ayahCount: 3 },
  { id: 104, nameArabic: "الهمزة", nameEnglish: "Al Humazah", translation: "The Traducer", revelation: "Makkah", ayahCount: 9 },
  { id: 105, nameArabic: "الفيل", nameEnglish: "Al Fil", translation: "The Elephant", revelation: "Makkah", ayahCount: 5 },
  { id: 106, nameArabic: "قريش", nameEnglish: "Quraysh", translation: "Quraysh", revelation: "Makkah", ayahCount: 4 },
  { id: 107, nameArabic: "الماعون", nameEnglish: "Al Ma'un", translation: "Small Kindnesses", revelation: "Makkah", ayahCount: 7 },
  { id: 108, nameArabic: "الكوثر", nameEnglish: "Al Kawthar", translation: "The Abundance", revelation: "Makkah", ayahCount: 3 },
  { id: 109, nameArabic: "الكافرون", nameEnglish: "Al Kafirun", translation: "The Disbelievers", revelation: "Makkah", ayahCount: 6 },
  { id: 110, nameArabic: "النصر", nameEnglish: "An Nasr", translation: "The Divine Support", revelation: "Madinah", ayahCount: 3 },
  { id: 111, nameArabic: "المسد", nameEnglish: "Al Masad", translation: "The Palm Fiber", revelation: "Makkah", ayahCount: 5 },
  { id: 112, nameArabic: "الإخلاص", nameEnglish: "Al Ikhlas", translation: "The Sincerity", revelation: "Makkah", ayahCount: 4 },
  { id: 113, nameArabic: "الفلق", nameEnglish: "Al Falaq", translation: "The Daybreak", revelation: "Makkah", ayahCount: 5 },
  { id: 114, nameArabic: "الناس", nameEnglish: "An Nas", translation: "Mankind", revelation: "Makkah", ayahCount: 6 },
];

export const getSurah = (id: number) => SURAHS.find((s) => s.id === id);

// Arabic-Indic digits
export const toArabicNumber = (n: number) =>
  n.toString().replace(/\d/g, (d) => "٠١٢٣٤٥٦٧٨٩"[Number(d)]);

// Audio URL: EveryAyah (Mishary Alafasy 128kbps)
export const ayahAudioUrl = (surahId: number, ayahId: number) => {
  const s = surahId.toString().padStart(3, "0");
  const a = ayahId.toString().padStart(3, "0");
  return `https://everyayah.com/data/Alafasy_128kbps/${s}${a}.mp3`;
};
