import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AppShell } from "@/components/layout/app-shell";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import AppProvider from "@/components/wrapper";
import { ThemeAndFontProvider } from "@/components/theme-provider";


const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",

  fallback: [
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Roboto",
    "Helvetica Neue",
    "Arial",
    "sans-serif",
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={cn("h-full",inter.variable, "font-sans","antialiased" )}
    >
      <body className="min-h-full flex flex-col">
<AppProvider >
 <ThemeAndFontProvider>
   <AppShell>
  {children}
</AppShell>
 </ThemeAndFontProvider>
</AppProvider>

      </body>
    </html>
  );
}
